### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by ShamrockLee** [alandefreitas/futures#11]
**Feature category**
- [ ] *enhancement - build system*
- [ ] *enhancement - backends*
- [ ] *enhancement - build system*
- [X] *enhancement - documentation*
- [ ] *enhancement - plot categories*

**The problem**

I was trying to port [clang-unformat](https://github.com/alandefreitas/clang-unformat) to support the recent version of futures, but have encounter compilation errors caused by breaking changes.

Considering that project is still 0.x.x and that breaking changes may happen between each two releases, providing some changelog would significantly enhance the library usability.

**The solution I'd like**

Add a file `CHANGELOG.md` at the project root and list each breaking change below the subtitle of the corresponding version. Whenever a breaking change is to be applied, the patch should add some lines to the `CHANGELOG.md`.

**Alternatives I've considered**

List / summarize the breaking changes in the release note along each release.

**Additional context**

Initial effort: https://github.com/alandefreitas/clang-unformat/issues/5#issuecomment-1322437342

**Comment by alandefreitas** [comment]
Is the changelog format I've been recently using for the releases OK (https://github.com/alandefreitas/futures/releases) or do you need something easier to parse? As you said, breaking changes are to be expected here and that's why I locked clang-unformat to futures v0.1.1 (https://github.com/alandefreitas/clang-unformat/blob/54d7ab3063580dea1f20f125956e44189a9dab88/CMakeLists.txt#L25).

**Comment by ShamrockLee** [comment]
Thanks for reply.

Does that mean it would be unrealistic to list all the changed function signature (due to the active development of this project)?

**Comment by ShamrockLee** [comment]
Oh, I got it. It's just `0.1.4`, four patches away from `0.1.0`.

Closing.

**Comment by alandefreitas** [comment]
> Does that mean it would be unrealistic to list all the changed function signature (due to the active development of this project)?

To be honest, I've never seen anything like this. That's the format we've been using:

- https://boostorg.github.io/outcome/changelog.html
- https://www.boost.org/users/history/version_1_80_0.html

This project uses something like that, with a few emojis to make it happier.

Breaking changes and new features are also listed, but the truth is we haven't had breaking changes in a while, because we are mainly including new features. We probably had a few breaking changes before adopting this changelog format though.

I think listing all code changes would be redundant because we can always just compare commits here. I imagine the current changelog should be more than enough for your use case. 

If you want, you can also update to the lastest version and show me whatever broke in your use case and I'll tell you how to fix it. I'm sure it's nothing big because we haven't broken anything serious lately.
